apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gzac-backend.fullname" . }}
  labels:
    {{- include "gzac-backend.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.settings.spring.profiles.active | quote }}
  SPRINGACTUATOR_USERNAME: {{ .Values.settings.spring.actuator.username | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.settings.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.settings.spring.datasource.username | quote }}
  KEYCLOAK_AUTHSERVERURL: {{ .Values.settings.keycloak.authServerURL | quote }}
  KEYCLOAK_RESOURCE: {{ .Values.settings.keycloak.clientID | quote }}
  KEYCLOAK_REALM: {{ .Values.settings.keycloak.realm | quote }}
  VALTIMO_KEYCLOAK_CLIENT: {{ .Values.settings.keycloak.client | quote }}
  VALTIMO_OAUTH_PUBLIC_KEY: {{ .Values.settings.keycloak.publicKey | quote }}
  VALTIMO_APP_HOSTNAME: {{ .Values.settings.gzac.appHostname | quote }}
  VALTIMO_DATABASE: {{ .Values.settings.gzac.databaseType | quote }}
  CAMUNDA_BPM_ADMINUSER_ID: {{ .Values.settings.camunda.adminUserID | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWT-SET-URI: {{ .Values.settings.spring.security.oauth2.resourceserver.jwt.jwk-set-uri | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAKJWT_ISSUER-URI: {{ .Values.settings.spring.security.oauth2.client.provider.keycloakjwt.issuer-uri | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAKAPI_ISSUER-URI: {{ .Values.settings.spring.security.oauth2.client.provider.keycloakapi.issuer-uri | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAKJWT_CLIENT-ID: {{ .Values.settings.spring.security.oauth2.client.registration.keycloakjwt.client-id | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAKAPI_CLIENT-ID: {{ .Values.settings.spring.security.oauth2.client.registration.keycloakapi.client-id | quote }}
